# Copyright 2025-present, Joseph Garnier
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
# =============================================================================
# What Is This?
# -------------
# See README file in the root directory of this source tree.

#-------------------------------------------------------------------------------
# Test of [CMakeTargetsFile module::GET_CONFIG_LIST operation]:
#   cmake_targets_file(GET_CONFIG_LIST <output-list-var> ALL_DEPS|REMOTE_DEPS|TARGETS)
ct_add_test(NAME "test_cmake_targets_file_get_config_list_operation")
function(${CMAKETEST_TEST})
  include(CMakeTargetsFile)

  # To call before each test
  macro(_set_up_test)
    # Reset properties used by `cmake_targets_file(GET_CONFIG_LIST)`
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED)
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS)
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS)
  endmacro()

  # Functionalities checking
  ct_add_section(NAME "get_all_dep_config_list")
  function(${CMAKETEST_SECTION})

    ct_add_section(NAME "global_property_is_not_set")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS" SET)
      ct_assert_false(output_property)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS")
      ct_assert_equal(output_property "")
      ct_assert_not_defined(output_property)

      cmake_targets_file(GET_CONFIG_LIST output ALL_DEPS)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS")
      ct_assert_equal(output_property "")
      ct_assert_not_defined(output_property)
      ct_assert_equal(output "")
      ct_assert_equal(output "${output_property}")
    endfunction()

    ct_add_section(NAME "global_property_is_empty")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
      set_property(GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS" "")
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS" SET)
      ct_assert_true(output_property)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS")
      ct_assert_equal(output_property "")
      ct_assert_defined(output_property)

      cmake_targets_file(GET_CONFIG_LIST output ALL_DEPS)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS")
      ct_assert_equal(output_property "")
      ct_assert_defined(output_property)
      ct_assert_equal(output "")
      ct_assert_equal(output "${output_property}")
    endfunction()

    ct_add_section(NAME "global_property_is_filled")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")

      cmake_targets_file(GET_CONFIG_LIST output ALL_DEPS)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS")
      ct_assert_equal(output_property "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
      ct_assert_defined(output_property)
      ct_assert_list(output)
      ct_assert_equal(output "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
      ct_assert_equal(output "${output_property}")
    endfunction()
  endfunction()

  ct_add_section(NAME "get_remote_dep_config_list")
  function(${CMAKETEST_SECTION})

    ct_add_section(NAME "global_property_is_not_set")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS" SET)
      ct_assert_false(output_property)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS")
      ct_assert_equal(output_property "")
      ct_assert_not_defined(output_property)

      cmake_targets_file(GET_CONFIG_LIST output REMOTE_DEPS)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS")
      ct_assert_equal(output_property "")
      ct_assert_not_defined(output_property)
      ct_assert_equal(output "")
      ct_assert_equal(output "${output_property}")
    endfunction()

    ct_add_section(NAME "global_property_is_empty")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
      set_property(GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS" "")
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS" SET)
      ct_assert_true(output_property)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS")
      ct_assert_equal(output_property "")
      ct_assert_defined(output_property)

      cmake_targets_file(GET_CONFIG_LIST output REMOTE_DEPS)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS")
      ct_assert_equal(output_property "")
      ct_assert_defined(output_property)
      ct_assert_equal(output "")
      ct_assert_equal(output "${output_property}")
    endfunction()

    ct_add_section(NAME "global_property_is_filled")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")

      cmake_targets_file(GET_CONFIG_LIST output REMOTE_DEPS)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_REMOTE_DEPS")
      ct_assert_equal(output_property "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
      ct_assert_defined(output_property)
      ct_assert_list(output)
      ct_assert_equal(output "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
      ct_assert_equal(output "${output_property}")
    endfunction()
  endfunction()

  ct_add_section(NAME "get_target_config_list")
  function(${CMAKETEST_SECTION})

    ct_add_section(NAME "global_property_is_not_set")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_TARGETS" SET)
      ct_assert_false(output_property)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_TARGETS")
      ct_assert_equal(output_property "")
      ct_assert_not_defined(output_property)

      cmake_targets_file(GET_CONFIG_LIST output TARGETS)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_TARGETS")
      ct_assert_equal(output_property "")
      ct_assert_not_defined(output_property)
      ct_assert_equal(output "")
      ct_assert_equal(output "${output_property}")
    endfunction()

    ct_add_section(NAME "global_property_is_empty")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
      set_property(GLOBAL PROPERTY "TARGETS_CONFIG_TARGETS" "")
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_TARGETS" SET)
      ct_assert_true(output_property)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_TARGETS")
      ct_assert_equal(output_property "")
      ct_assert_defined(output_property)

      cmake_targets_file(GET_CONFIG_LIST output TARGETS)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_TARGETS")
      ct_assert_equal(output_property "")
      ct_assert_defined(output_property)
      ct_assert_equal(output "")
      ct_assert_equal(output "${output_property}")
    endfunction()

    ct_add_section(NAME "global_property_is_filled")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS "src;src/grape;src/lemon")

      cmake_targets_file(GET_CONFIG_LIST output TARGETS)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_TARGETS")
      ct_assert_equal(output_property "src;src/grape;src/lemon")
      ct_assert_defined(output_property)
      ct_assert_list(output)
      ct_assert_equal(output "src;src/grape;src/lemon")
      ct_assert_equal(output "${output_property}")
    endfunction()
  endfunction()

  # Errors checking
  ct_add_section(NAME "throws_if_arg_output_list_var_is_missing_1" EXPECTFAIL)
  function(${CMAKETEST_SECTION})
    _set_up_test()
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS "src;src/grape;src/lemon")
    cmake_targets_file(GET_CONFIG_LIST TARGETS)
  endfunction()

  ct_add_section(NAME "throws_if_arg_output_var_is_missing_2" EXPECTFAIL)
  function(${CMAKETEST_SECTION})
    _set_up_test()
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS "src;src/grape;src/lemon")
    cmake_targets_file(GET_CONFIG_LIST "" TARGETS)
  endfunction()

  ct_add_section(NAME "throws_if_arg_output_var_is_missing_3" EXPECTFAIL)
  function(${CMAKETEST_SECTION})
    _set_up_test()
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS "src;src/grape;src/lemon")
    cmake_targets_file(GET_CONFIG_LIST "output" TARGETS)
  endfunction()

  ct_add_section(NAME "throws_if_arg_config_type_is_missing" EXPECTFAIL)
  function(${CMAKETEST_SECTION})
    _set_up_test()
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS "src;src/grape;src/lemon")
    cmake_targets_file(GET_CONFIG_LIST output)
  endfunction()

  ct_add_section(NAME "throws_if_arg_config_type_is_twice" EXPECTFAIL)
  function(${CMAKETEST_SECTION})
    _set_up_test()
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED true)
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
    set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS "src;src/grape;src/lemon")
    cmake_targets_file(GET_CONFIG_LIST output ALL_DEPS REMOTE_DEPS TARGETS)
  endfunction()

  ct_add_section(NAME "throws_if_config_file_is_not_loaded")
  function(${CMAKETEST_SECTION})

    ct_add_section(NAME "throws_if_global_property_is_not_set")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_LOADED" SET)
      ct_assert_false(output_property)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_LOADED")
      ct_assert_equal(output_property "")
      ct_assert_not_defined(output_property)
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS "src;src/grape;src/lemon")

      ct_add_section(NAME "throws_if_global_property_is_not_set_inner_1" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output ALL_DEPS)
      endfunction()

      ct_add_section(NAME "throws_if_global_property_is_not_set_inner_2" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output REMOTE_DEPS)
      endfunction()

      ct_add_section(NAME "throws_if_global_property_is_not_set_inner_3" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output TARGETS)
      endfunction()
    endfunction()

    ct_add_section(NAME "throws_if_global_property_is_empty")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED "")
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_LOADED" SET)
      ct_assert_true(output_property)
      get_property(output_property GLOBAL PROPERTY "TARGETS_CONFIG_LOADED")
      ct_assert_equal(output_property "")
      ct_assert_defined(output_property)
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS "src;src/grape;src/lemon")

      ct_add_section(NAME "throws_if_global_property_is_empty_inner_1" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output ALL_DEPS)
      endfunction()

      ct_add_section(NAME "throws_if_global_property_is_empty_inner_2" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output REMOTE_DEPS)
      endfunction()

      ct_add_section(NAME "throws_if_global_property_is_empty_inner_3" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output TARGETS)
      endfunction()
    endfunction()

    ct_add_section(NAME "throws_if_global_property_is_not_bool")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED "not-bool")
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS "src;src/grape;src/lemon")

      ct_add_section(NAME "throws_if_global_property_is_not_bool_inner_1" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output ALL_DEPS)
      endfunction()

      ct_add_section(NAME "throws_if_global_property_is_not_bool_inner_2" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output REMOTE_DEPS)
      endfunction()

      ct_add_section(NAME "throws_if_global_property_is_not_bool_inner_3" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output TARGETS)
      endfunction()
    endfunction()

    ct_add_section(NAME "throws_if_global_property_is_false")
    function(${CMAKETEST_SECTION})
      _set_up_test()
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_LOADED false)
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_REMOTE_DEPS "AppleLib;BananaLib;CarrotLib;OrangeLib;PineappleLib")
      set_property(GLOBAL PROPERTY TARGETS_CONFIG_TARGETS "src;src/grape;src/lemon")

      ct_add_section(NAME "throws_if_global_property_is_false_inner_1" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output ALL_DEPS)
      endfunction()

      ct_add_section(NAME "throws_if_global_property_is_false_inner_2" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output REMOTE_DEPS)
      endfunction()

      ct_add_section(NAME "throws_if_global_property_is_false_inner_3" EXPECTFAIL)
      function(${CMAKETEST_SECTION})
        cmake_targets_file(GET_CONFIG_LIST output TARGETS)
      endfunction()
    endfunction()
  endfunction()
endfunction()
